name: default
dependencies:
- astroid=1.4.4=py27_0
- coverage=4.2=py27_0
- enum34=1.1.6=py27_0
- lazy-object-proxy=1.2.1=py27_0
- logilab-common=1.0.2=py27_0
- nose=1.3.7=py27_1
- openssl=1.0.2h=2
- pip=8.1.2=py27_0
- pylint=1.5.4=py27_0
- python=2.7.12=1
- readline=6.2=2
- setuptools=26.1.1=py27_0
- singledispatch=3.4.0.3=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- wrapt=1.10.6=py27_0
- zlib=1.2.8=3

